// Server-only helpers: render Liquidsoap & Icecast configs from DB rows.
// Pure string builders — safe to call from server functions or route handlers.

export type StationRow = { id: string; name: string; slug: string };
export type IcecastRow = {
  hostname: string; port: number;
  admin_user: string; admin_password: string;
  source_password: string; relay_password: string;
  max_clients: number; max_sources: number;
  location: string | null; admin_email: string | null;
};
export type MountRow = { mount_path: string; format: string; bitrate: number; is_default: boolean };
export type LiqRow = {
  crossfade_seconds: number; normalize_audio: boolean;
  fallback_track_path: string | null; custom_liq: string | null;
  telnet_host: string; telnet_port: number;
};
export type PlaylistEntry = { name: string; weight: number; files: string[] };
export type LiveInputRow = {
  mount_path: string; harbor_port: number;
  source_user: string; source_password: string;
  format: string; bitrate: number;
  auto_takeover: boolean; forced_takeover: boolean;
  fade_in_seconds: number; fade_out_seconds: number;
  is_enabled: boolean;
};

const xmlEscape = (s: string) => s.replace(/[<>&"]/g, (c) =>
  ({ "<": "&lt;", ">": "&gt;", "&": "&amp;", '"': "&quot;" }[c]!));

export function renderIcecastXml(station: StationRow, ic: IcecastRow, mounts: MountRow[]): string {
  const mountsXml = mounts.map((m) => `
  <mount type="normal">
    <mount-name>${xmlEscape(m.mount_path)}</mount-name>
    <max-listeners>${ic.max_clients}</max-listeners>
    <public>1</public>
    <stream-name>${xmlEscape(station.name)}</stream-name>
    <bitrate>${m.bitrate}</bitrate>
    <type>audio/${m.format === "ogg" ? "ogg" : "mpeg"}</type>
  </mount>`).join("\n");

  return `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by Radio Core for ${xmlEscape(station.name)} (${xmlEscape(station.slug)}) -->
<icecast>
  <location>${xmlEscape(ic.location ?? "Sweden")}</location>
  <admin>${xmlEscape(ic.admin_email ?? "admin@example.com")}</admin>
  <limits>
    <clients>${ic.max_clients}</clients>
    <sources>${ic.max_sources}</sources>
    <queue-size>524288</queue-size>
    <client-timeout>30</client-timeout>
    <header-timeout>15</header-timeout>
    <source-timeout>10</source-timeout>
    <burst-on-connect>1</burst-on-connect>
    <burst-size>65535</burst-size>
  </limits>
  <authentication>
    <source-password>${xmlEscape(ic.source_password)}</source-password>
    <relay-password>${xmlEscape(ic.relay_password)}</relay-password>
    <admin-user>${xmlEscape(ic.admin_user)}</admin-user>
    <admin-password>${xmlEscape(ic.admin_password)}</admin-password>
  </authentication>
  <hostname>${xmlEscape(ic.hostname)}</hostname>
  <listen-socket>
    <port>${ic.port}</port>
  </listen-socket>
${mountsXml}
  <fileserve>1</fileserve>
  <paths>
    <basedir>/usr/share/icecast</basedir>
    <logdir>/var/log/icecast</logdir>
    <webroot>/usr/share/icecast/web</webroot>
    <adminroot>/usr/share/icecast/admin</adminroot>
    <pidfile>/var/run/icecast/icecast.pid</pidfile>
    <alias source="/" destination="/status.xsl"/>
  </paths>
  <logging>
    <accesslog>access.log</accesslog>
    <errorlog>error.log</errorlog>
    <loglevel>3</loglevel>
    <logsize>10000</logsize>
  </logging>
</icecast>
`;
}

export function renderLiquidsoapLiq(
  station: StationRow,
  ic: IcecastRow,
  mount: MountRow,
  liq: LiqRow,
  playlists: PlaylistEntry[],
  apiBaseUrl: string,
  stackToken: string,
): string {
  const stationDir = `/data/stations/${station.slug}`;
  const playlistBlocks = playlists.map((p, i) => {
    const safe = `pl_${i}_${p.name.toLowerCase().replace(/[^a-z0-9]+/g, "_")}`;
    return `${safe} = playlist(reload=300, mode="randomize", "${stationDir}/playlists/${safe}.m3u")`;
  }).join("\n");

  const sources = playlists.length
    ? playlists.map((_, i) => `pl_${i}_${playlists[i].name.toLowerCase().replace(/[^a-z0-9]+/g, "_")}`).join(", ")
    : "";

  const fallbackTrack = liq.fallback_track_path
    ? `single("${liq.fallback_track_path}")`
    : `blank(duration=2.0)`;

  const radio = playlists.length
    ? `radio = random(weights=[${playlists.map((p) => p.weight || 1).join(", ")}], [${sources}])`
    : `radio = ${fallbackTrack}`;

  const normalize = liq.normalize_audio ? `radio = normalize(radio)` : `# normalize disabled`;

  return `# Generated by Radio Core for ${station.name} (${station.slug})
# Do not edit manually — regenerated by control plane.

settings.log.file.path.set("${stationDir}/logs/liquidsoap.log")
settings.server.telnet.set(true)
settings.server.telnet.bind_addr.set("0.0.0.0")
settings.server.telnet.port.set(${liq.telnet_port})

${playlistBlocks}

security = ${fallbackTrack}

${radio}
${normalize}
radio = crossfade(duration=${liq.crossfade_seconds}, radio)
radio = fallback(track_sensitive=false, [radio, security])

# Notify Radio Core on metadata change
def on_meta(m) =
  title = m["title"]
  artist = m["artist"]
  album = m["album"]
  ignore(http.post(
    headers=[("content-type","application/json"),("x-stack-token","${stackToken}")],
    data=json.stringify(record(
      station_slug="${station.slug}",
      title=title, artist=artist, album=album,
      mount="${mount.mount_path}"
    )),
    "${apiBaseUrl}/api/public/now-playing"
  ))
end
radio = source.on_metadata(radio, on_meta)

output.icecast(
  %${mount.format === "ogg" ? "vorbis" : "mp3"}(bitrate=${mount.bitrate}),
  host = "${ic.hostname}",
  port = ${ic.port},
  password = "${ic.source_password}",
  mount = "${mount.mount_path}",
  name = "${station.name}",
  description = "Radio Core stream for ${station.name}",
  genre = "Various",
  url = "https://${ic.hostname}:${ic.port}${mount.mount_path}",
  radio
)
`;
}

export function renderM3u(absolutePaths: string[]): string {
  return ["#EXTM3U", ...absolutePaths].join("\n") + "\n";
}
