name: radio-core

services:
  radio-core-api:
    build:
      context: ../backend/api
      target: development
    environment:
      NODE_ENV: development
    volumes:
      - ../backend/api:/app
      - /app/node_modules

  mongodb:
    ports:
      - "27017:27017"

