/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VoicetracksRouteImport } from './routes/voicetracks'
import { Route as UsersRouteImport } from './routes/users'
import { Route as SyncJobsRouteImport } from './routes/sync-jobs'
import { Route as StreamingOutputsRouteImport } from './routes/streaming-outputs'
import { Route as StreamingRouteImport } from './routes/streaming'
import { Route as StorageTargetsRouteImport } from './routes/storage-targets'
import { Route as StorageRouteImport } from './routes/storage'
import { Route as StationsRouteImport } from './routes/stations'
import { Route as ShowsRouteImport } from './routes/shows'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SchedulerRouteImport } from './routes/scheduler'
import { Route as RuntimeTargetsRouteImport } from './routes/runtime-targets'
import { Route as RotationRouteImport } from './routes/rotation'
import { Route as R2StorageRouteImport } from './routes/r2-storage'
import { Route as PlaylistsRouteImport } from './routes/playlists'
import { Route as NowPlayingRouteImport } from './routes/now-playing'
import { Route as MediaRouteImport } from './routes/media'
import { Route as LiveRouteImport } from './routes/live'
import { Route as ListenersRouteImport } from './routes/listeners'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as HealthRouteImport } from './routes/health'
import { Route as FilesRouteImport } from './routes/files'
import { Route as FallbackRouteImport } from './routes/fallback'
import { Route as EpisodesRouteImport } from './routes/episodes'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as ConfigsRouteImport } from './routes/configs'
import { Route as CompanionRouteImport } from './routes/companion'
import { Route as CockpitRouteImport } from './routes/cockpit'
import { Route as BackupRouteImport } from './routes/backup'
import { Route as AzuracastRouteImport } from './routes/azuracast'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as AdsRouteImport } from './routes/ads'
import { Route as AccountsRouteImport } from './routes/accounts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MetadataIndexRouteImport } from './routes/metadata.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as MetadataIdRouteImport } from './routes/metadata.$id'
import { Route as ApiPublicStationConfigRouteImport } from './routes/api.public.station-config'
import { Route as ApiPublicNowPlayingRouteImport } from './routes/api.public.now-playing'
import { Route as ApiPublicListenerStatsRouteImport } from './routes/api.public.listener-stats'
import { Route as ApiPublicHealthRouteImport } from './routes/api.public.health'
import { Route as ApiPublicCronSyncWorkerRouteImport } from './routes/api.public.cron.sync-worker'

const VoicetracksRoute = VoicetracksRouteImport.update({
  id: '/voicetracks',
  path: '/voicetracks',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SyncJobsRoute = SyncJobsRouteImport.update({
  id: '/sync-jobs',
  path: '/sync-jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const StreamingOutputsRoute = StreamingOutputsRouteImport.update({
  id: '/streaming-outputs',
  path: '/streaming-outputs',
  getParentRoute: () => rootRouteImport,
} as any)
const StreamingRoute = StreamingRouteImport.update({
  id: '/streaming',
  path: '/streaming',
  getParentRoute: () => rootRouteImport,
} as any)
const StorageTargetsRoute = StorageTargetsRouteImport.update({
  id: '/storage-targets',
  path: '/storage-targets',
  getParentRoute: () => rootRouteImport,
} as any)
const StorageRoute = StorageRouteImport.update({
  id: '/storage',
  path: '/storage',
  getParentRoute: () => rootRouteImport,
} as any)
const StationsRoute = StationsRouteImport.update({
  id: '/stations',
  path: '/stations',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowsRoute = ShowsRouteImport.update({
  id: '/shows',
  path: '/shows',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SchedulerRoute = SchedulerRouteImport.update({
  id: '/scheduler',
  path: '/scheduler',
  getParentRoute: () => rootRouteImport,
} as any)
const RuntimeTargetsRoute = RuntimeTargetsRouteImport.update({
  id: '/runtime-targets',
  path: '/runtime-targets',
  getParentRoute: () => rootRouteImport,
} as any)
const RotationRoute = RotationRouteImport.update({
  id: '/rotation',
  path: '/rotation',
  getParentRoute: () => rootRouteImport,
} as any)
const R2StorageRoute = R2StorageRouteImport.update({
  id: '/r2-storage',
  path: '/r2-storage',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistsRoute = PlaylistsRouteImport.update({
  id: '/playlists',
  path: '/playlists',
  getParentRoute: () => rootRouteImport,
} as any)
const NowPlayingRoute = NowPlayingRouteImport.update({
  id: '/now-playing',
  path: '/now-playing',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaRoute = MediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const ListenersRoute = ListenersRouteImport.update({
  id: '/listeners',
  path: '/listeners',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesRoute = FilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => rootRouteImport,
} as any)
const FallbackRoute = FallbackRouteImport.update({
  id: '/fallback',
  path: '/fallback',
  getParentRoute: () => rootRouteImport,
} as any)
const EpisodesRoute = EpisodesRouteImport.update({
  id: '/episodes',
  path: '/episodes',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigsRoute = ConfigsRouteImport.update({
  id: '/configs',
  path: '/configs',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanionRoute = CompanionRouteImport.update({
  id: '/companion',
  path: '/companion',
  getParentRoute: () => rootRouteImport,
} as any)
const CockpitRoute = CockpitRouteImport.update({
  id: '/cockpit',
  path: '/cockpit',
  getParentRoute: () => rootRouteImport,
} as any)
const BackupRoute = BackupRouteImport.update({
  id: '/backup',
  path: '/backup',
  getParentRoute: () => rootRouteImport,
} as any)
const AzuracastRoute = AzuracastRouteImport.update({
  id: '/azuracast',
  path: '/azuracast',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const AdsRoute = AdsRouteImport.update({
  id: '/ads',
  path: '/ads',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MetadataIndexRoute = MetadataIndexRouteImport.update({
  id: '/metadata/',
  path: '/metadata/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const MetadataIdRoute = MetadataIdRouteImport.update({
  id: '/metadata/$id',
  path: '/metadata/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicStationConfigRoute = ApiPublicStationConfigRouteImport.update({
  id: '/api/public/station-config',
  path: '/api/public/station-config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicNowPlayingRoute = ApiPublicNowPlayingRouteImport.update({
  id: '/api/public/now-playing',
  path: '/api/public/now-playing',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicListenerStatsRoute = ApiPublicListenerStatsRouteImport.update({
  id: '/api/public/listener-stats',
  path: '/api/public/listener-stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHealthRoute = ApiPublicHealthRouteImport.update({
  id: '/api/public/health',
  path: '/api/public/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronSyncWorkerRoute = ApiPublicCronSyncWorkerRouteImport.update({
  id: '/api/public/cron/sync-worker',
  path: '/api/public/cron/sync-worker',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/ads': typeof AdsRoute
  '/agents': typeof AgentsRoute
  '/audit': typeof AuditRoute
  '/auth': typeof AuthRoute
  '/azuracast': typeof AzuracastRoute
  '/backup': typeof BackupRoute
  '/cockpit': typeof CockpitRoute
  '/companion': typeof CompanionRoute
  '/configs': typeof ConfigsRoute
  '/demo': typeof DemoRoute
  '/episodes': typeof EpisodesRoute
  '/fallback': typeof FallbackRoute
  '/files': typeof FilesRoute
  '/health': typeof HealthRoute
  '/inbox': typeof InboxRoute
  '/listeners': typeof ListenersRoute
  '/live': typeof LiveRoute
  '/media': typeof MediaRoute
  '/now-playing': typeof NowPlayingRoute
  '/playlists': typeof PlaylistsRoute
  '/r2-storage': typeof R2StorageRoute
  '/rotation': typeof RotationRoute
  '/runtime-targets': typeof RuntimeTargetsRoute
  '/scheduler': typeof SchedulerRoute
  '/settings': typeof SettingsRoute
  '/shows': typeof ShowsRoute
  '/stations': typeof StationsRoute
  '/storage': typeof StorageRoute
  '/storage-targets': typeof StorageTargetsRoute
  '/streaming': typeof StreamingRoute
  '/streaming-outputs': typeof StreamingOutputsRoute
  '/sync-jobs': typeof SyncJobsRoute
  '/users': typeof UsersRoute
  '/voicetracks': typeof VoicetracksRoute
  '/metadata/$id': typeof MetadataIdRoute
  '/admin/': typeof AdminIndexRoute
  '/metadata/': typeof MetadataIndexRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/listener-stats': typeof ApiPublicListenerStatsRoute
  '/api/public/now-playing': typeof ApiPublicNowPlayingRoute
  '/api/public/station-config': typeof ApiPublicStationConfigRoute
  '/api/public/cron/sync-worker': typeof ApiPublicCronSyncWorkerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/ads': typeof AdsRoute
  '/agents': typeof AgentsRoute
  '/audit': typeof AuditRoute
  '/auth': typeof AuthRoute
  '/azuracast': typeof AzuracastRoute
  '/backup': typeof BackupRoute
  '/cockpit': typeof CockpitRoute
  '/companion': typeof CompanionRoute
  '/configs': typeof ConfigsRoute
  '/demo': typeof DemoRoute
  '/episodes': typeof EpisodesRoute
  '/fallback': typeof FallbackRoute
  '/files': typeof FilesRoute
  '/health': typeof HealthRoute
  '/inbox': typeof InboxRoute
  '/listeners': typeof ListenersRoute
  '/live': typeof LiveRoute
  '/media': typeof MediaRoute
  '/now-playing': typeof NowPlayingRoute
  '/playlists': typeof PlaylistsRoute
  '/r2-storage': typeof R2StorageRoute
  '/rotation': typeof RotationRoute
  '/runtime-targets': typeof RuntimeTargetsRoute
  '/scheduler': typeof SchedulerRoute
  '/settings': typeof SettingsRoute
  '/shows': typeof ShowsRoute
  '/stations': typeof StationsRoute
  '/storage': typeof StorageRoute
  '/storage-targets': typeof StorageTargetsRoute
  '/streaming': typeof StreamingRoute
  '/streaming-outputs': typeof StreamingOutputsRoute
  '/sync-jobs': typeof SyncJobsRoute
  '/users': typeof UsersRoute
  '/voicetracks': typeof VoicetracksRoute
  '/metadata/$id': typeof MetadataIdRoute
  '/admin': typeof AdminIndexRoute
  '/metadata': typeof MetadataIndexRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/listener-stats': typeof ApiPublicListenerStatsRoute
  '/api/public/now-playing': typeof ApiPublicNowPlayingRoute
  '/api/public/station-config': typeof ApiPublicStationConfigRoute
  '/api/public/cron/sync-worker': typeof ApiPublicCronSyncWorkerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/ads': typeof AdsRoute
  '/agents': typeof AgentsRoute
  '/audit': typeof AuditRoute
  '/auth': typeof AuthRoute
  '/azuracast': typeof AzuracastRoute
  '/backup': typeof BackupRoute
  '/cockpit': typeof CockpitRoute
  '/companion': typeof CompanionRoute
  '/configs': typeof ConfigsRoute
  '/demo': typeof DemoRoute
  '/episodes': typeof EpisodesRoute
  '/fallback': typeof FallbackRoute
  '/files': typeof FilesRoute
  '/health': typeof HealthRoute
  '/inbox': typeof InboxRoute
  '/listeners': typeof ListenersRoute
  '/live': typeof LiveRoute
  '/media': typeof MediaRoute
  '/now-playing': typeof NowPlayingRoute
  '/playlists': typeof PlaylistsRoute
  '/r2-storage': typeof R2StorageRoute
  '/rotation': typeof RotationRoute
  '/runtime-targets': typeof RuntimeTargetsRoute
  '/scheduler': typeof SchedulerRoute
  '/settings': typeof SettingsRoute
  '/shows': typeof ShowsRoute
  '/stations': typeof StationsRoute
  '/storage': typeof StorageRoute
  '/storage-targets': typeof StorageTargetsRoute
  '/streaming': typeof StreamingRoute
  '/streaming-outputs': typeof StreamingOutputsRoute
  '/sync-jobs': typeof SyncJobsRoute
  '/users': typeof UsersRoute
  '/voicetracks': typeof VoicetracksRoute
  '/metadata/$id': typeof MetadataIdRoute
  '/admin/': typeof AdminIndexRoute
  '/metadata/': typeof MetadataIndexRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/listener-stats': typeof ApiPublicListenerStatsRoute
  '/api/public/now-playing': typeof ApiPublicNowPlayingRoute
  '/api/public/station-config': typeof ApiPublicStationConfigRoute
  '/api/public/cron/sync-worker': typeof ApiPublicCronSyncWorkerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts'
    | '/ads'
    | '/agents'
    | '/audit'
    | '/auth'
    | '/azuracast'
    | '/backup'
    | '/cockpit'
    | '/companion'
    | '/configs'
    | '/demo'
    | '/episodes'
    | '/fallback'
    | '/files'
    | '/health'
    | '/inbox'
    | '/listeners'
    | '/live'
    | '/media'
    | '/now-playing'
    | '/playlists'
    | '/r2-storage'
    | '/rotation'
    | '/runtime-targets'
    | '/scheduler'
    | '/settings'
    | '/shows'
    | '/stations'
    | '/storage'
    | '/storage-targets'
    | '/streaming'
    | '/streaming-outputs'
    | '/sync-jobs'
    | '/users'
    | '/voicetracks'
    | '/metadata/$id'
    | '/admin/'
    | '/metadata/'
    | '/api/public/health'
    | '/api/public/listener-stats'
    | '/api/public/now-playing'
    | '/api/public/station-config'
    | '/api/public/cron/sync-worker'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounts'
    | '/ads'
    | '/agents'
    | '/audit'
    | '/auth'
    | '/azuracast'
    | '/backup'
    | '/cockpit'
    | '/companion'
    | '/configs'
    | '/demo'
    | '/episodes'
    | '/fallback'
    | '/files'
    | '/health'
    | '/inbox'
    | '/listeners'
    | '/live'
    | '/media'
    | '/now-playing'
    | '/playlists'
    | '/r2-storage'
    | '/rotation'
    | '/runtime-targets'
    | '/scheduler'
    | '/settings'
    | '/shows'
    | '/stations'
    | '/storage'
    | '/storage-targets'
    | '/streaming'
    | '/streaming-outputs'
    | '/sync-jobs'
    | '/users'
    | '/voicetracks'
    | '/metadata/$id'
    | '/admin'
    | '/metadata'
    | '/api/public/health'
    | '/api/public/listener-stats'
    | '/api/public/now-playing'
    | '/api/public/station-config'
    | '/api/public/cron/sync-worker'
  id:
    | '__root__'
    | '/'
    | '/accounts'
    | '/ads'
    | '/agents'
    | '/audit'
    | '/auth'
    | '/azuracast'
    | '/backup'
    | '/cockpit'
    | '/companion'
    | '/configs'
    | '/demo'
    | '/episodes'
    | '/fallback'
    | '/files'
    | '/health'
    | '/inbox'
    | '/listeners'
    | '/live'
    | '/media'
    | '/now-playing'
    | '/playlists'
    | '/r2-storage'
    | '/rotation'
    | '/runtime-targets'
    | '/scheduler'
    | '/settings'
    | '/shows'
    | '/stations'
    | '/storage'
    | '/storage-targets'
    | '/streaming'
    | '/streaming-outputs'
    | '/sync-jobs'
    | '/users'
    | '/voicetracks'
    | '/metadata/$id'
    | '/admin/'
    | '/metadata/'
    | '/api/public/health'
    | '/api/public/listener-stats'
    | '/api/public/now-playing'
    | '/api/public/station-config'
    | '/api/public/cron/sync-worker'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountsRoute: typeof AccountsRoute
  AdsRoute: typeof AdsRoute
  AgentsRoute: typeof AgentsRoute
  AuditRoute: typeof AuditRoute
  AuthRoute: typeof AuthRoute
  AzuracastRoute: typeof AzuracastRoute
  BackupRoute: typeof BackupRoute
  CockpitRoute: typeof CockpitRoute
  CompanionRoute: typeof CompanionRoute
  ConfigsRoute: typeof ConfigsRoute
  DemoRoute: typeof DemoRoute
  EpisodesRoute: typeof EpisodesRoute
  FallbackRoute: typeof FallbackRoute
  FilesRoute: typeof FilesRoute
  HealthRoute: typeof HealthRoute
  InboxRoute: typeof InboxRoute
  ListenersRoute: typeof ListenersRoute
  LiveRoute: typeof LiveRoute
  MediaRoute: typeof MediaRoute
  NowPlayingRoute: typeof NowPlayingRoute
  PlaylistsRoute: typeof PlaylistsRoute
  R2StorageRoute: typeof R2StorageRoute
  RotationRoute: typeof RotationRoute
  RuntimeTargetsRoute: typeof RuntimeTargetsRoute
  SchedulerRoute: typeof SchedulerRoute
  SettingsRoute: typeof SettingsRoute
  ShowsRoute: typeof ShowsRoute
  StationsRoute: typeof StationsRoute
  StorageRoute: typeof StorageRoute
  StorageTargetsRoute: typeof StorageTargetsRoute
  StreamingRoute: typeof StreamingRoute
  StreamingOutputsRoute: typeof StreamingOutputsRoute
  SyncJobsRoute: typeof SyncJobsRoute
  UsersRoute: typeof UsersRoute
  VoicetracksRoute: typeof VoicetracksRoute
  MetadataIdRoute: typeof MetadataIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  MetadataIndexRoute: typeof MetadataIndexRoute
  ApiPublicHealthRoute: typeof ApiPublicHealthRoute
  ApiPublicListenerStatsRoute: typeof ApiPublicListenerStatsRoute
  ApiPublicNowPlayingRoute: typeof ApiPublicNowPlayingRoute
  ApiPublicStationConfigRoute: typeof ApiPublicStationConfigRoute
  ApiPublicCronSyncWorkerRoute: typeof ApiPublicCronSyncWorkerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/voicetracks': {
      id: '/voicetracks'
      path: '/voicetracks'
      fullPath: '/voicetracks'
      preLoaderRoute: typeof VoicetracksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sync-jobs': {
      id: '/sync-jobs'
      path: '/sync-jobs'
      fullPath: '/sync-jobs'
      preLoaderRoute: typeof SyncJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/streaming-outputs': {
      id: '/streaming-outputs'
      path: '/streaming-outputs'
      fullPath: '/streaming-outputs'
      preLoaderRoute: typeof StreamingOutputsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/streaming': {
      id: '/streaming'
      path: '/streaming'
      fullPath: '/streaming'
      preLoaderRoute: typeof StreamingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/storage-targets': {
      id: '/storage-targets'
      path: '/storage-targets'
      fullPath: '/storage-targets'
      preLoaderRoute: typeof StorageTargetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/storage': {
      id: '/storage'
      path: '/storage'
      fullPath: '/storage'
      preLoaderRoute: typeof StorageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stations': {
      id: '/stations'
      path: '/stations'
      fullPath: '/stations'
      preLoaderRoute: typeof StationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shows': {
      id: '/shows'
      path: '/shows'
      fullPath: '/shows'
      preLoaderRoute: typeof ShowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scheduler': {
      id: '/scheduler'
      path: '/scheduler'
      fullPath: '/scheduler'
      preLoaderRoute: typeof SchedulerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runtime-targets': {
      id: '/runtime-targets'
      path: '/runtime-targets'
      fullPath: '/runtime-targets'
      preLoaderRoute: typeof RuntimeTargetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rotation': {
      id: '/rotation'
      path: '/rotation'
      fullPath: '/rotation'
      preLoaderRoute: typeof RotationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r2-storage': {
      id: '/r2-storage'
      path: '/r2-storage'
      fullPath: '/r2-storage'
      preLoaderRoute: typeof R2StorageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlists': {
      id: '/playlists'
      path: '/playlists'
      fullPath: '/playlists'
      preLoaderRoute: typeof PlaylistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/now-playing': {
      id: '/now-playing'
      path: '/now-playing'
      fullPath: '/now-playing'
      preLoaderRoute: typeof NowPlayingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media': {
      id: '/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof MediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listeners': {
      id: '/listeners'
      path: '/listeners'
      fullPath: '/listeners'
      preLoaderRoute: typeof ListenersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files': {
      id: '/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof FilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fallback': {
      id: '/fallback'
      path: '/fallback'
      fullPath: '/fallback'
      preLoaderRoute: typeof FallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/episodes': {
      id: '/episodes'
      path: '/episodes'
      fullPath: '/episodes'
      preLoaderRoute: typeof EpisodesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configs': {
      id: '/configs'
      path: '/configs'
      fullPath: '/configs'
      preLoaderRoute: typeof ConfigsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companion': {
      id: '/companion'
      path: '/companion'
      fullPath: '/companion'
      preLoaderRoute: typeof CompanionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cockpit': {
      id: '/cockpit'
      path: '/cockpit'
      fullPath: '/cockpit'
      preLoaderRoute: typeof CockpitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backup': {
      id: '/backup'
      path: '/backup'
      fullPath: '/backup'
      preLoaderRoute: typeof BackupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/azuracast': {
      id: '/azuracast'
      path: '/azuracast'
      fullPath: '/azuracast'
      preLoaderRoute: typeof AzuracastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ads': {
      id: '/ads'
      path: '/ads'
      fullPath: '/ads'
      preLoaderRoute: typeof AdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metadata/': {
      id: '/metadata/'
      path: '/metadata'
      fullPath: '/metadata/'
      preLoaderRoute: typeof MetadataIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metadata/$id': {
      id: '/metadata/$id'
      path: '/metadata/$id'
      fullPath: '/metadata/$id'
      preLoaderRoute: typeof MetadataIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/station-config': {
      id: '/api/public/station-config'
      path: '/api/public/station-config'
      fullPath: '/api/public/station-config'
      preLoaderRoute: typeof ApiPublicStationConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/now-playing': {
      id: '/api/public/now-playing'
      path: '/api/public/now-playing'
      fullPath: '/api/public/now-playing'
      preLoaderRoute: typeof ApiPublicNowPlayingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/listener-stats': {
      id: '/api/public/listener-stats'
      path: '/api/public/listener-stats'
      fullPath: '/api/public/listener-stats'
      preLoaderRoute: typeof ApiPublicListenerStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/health': {
      id: '/api/public/health'
      path: '/api/public/health'
      fullPath: '/api/public/health'
      preLoaderRoute: typeof ApiPublicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/sync-worker': {
      id: '/api/public/cron/sync-worker'
      path: '/api/public/cron/sync-worker'
      fullPath: '/api/public/cron/sync-worker'
      preLoaderRoute: typeof ApiPublicCronSyncWorkerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountsRoute: AccountsRoute,
  AdsRoute: AdsRoute,
  AgentsRoute: AgentsRoute,
  AuditRoute: AuditRoute,
  AuthRoute: AuthRoute,
  AzuracastRoute: AzuracastRoute,
  BackupRoute: BackupRoute,
  CockpitRoute: CockpitRoute,
  CompanionRoute: CompanionRoute,
  ConfigsRoute: ConfigsRoute,
  DemoRoute: DemoRoute,
  EpisodesRoute: EpisodesRoute,
  FallbackRoute: FallbackRoute,
  FilesRoute: FilesRoute,
  HealthRoute: HealthRoute,
  InboxRoute: InboxRoute,
  ListenersRoute: ListenersRoute,
  LiveRoute: LiveRoute,
  MediaRoute: MediaRoute,
  NowPlayingRoute: NowPlayingRoute,
  PlaylistsRoute: PlaylistsRoute,
  R2StorageRoute: R2StorageRoute,
  RotationRoute: RotationRoute,
  RuntimeTargetsRoute: RuntimeTargetsRoute,
  SchedulerRoute: SchedulerRoute,
  SettingsRoute: SettingsRoute,
  ShowsRoute: ShowsRoute,
  StationsRoute: StationsRoute,
  StorageRoute: StorageRoute,
  StorageTargetsRoute: StorageTargetsRoute,
  StreamingRoute: StreamingRoute,
  StreamingOutputsRoute: StreamingOutputsRoute,
  SyncJobsRoute: SyncJobsRoute,
  UsersRoute: UsersRoute,
  VoicetracksRoute: VoicetracksRoute,
  MetadataIdRoute: MetadataIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  MetadataIndexRoute: MetadataIndexRoute,
  ApiPublicHealthRoute: ApiPublicHealthRoute,
  ApiPublicListenerStatsRoute: ApiPublicListenerStatsRoute,
  ApiPublicNowPlayingRoute: ApiPublicNowPlayingRoute,
  ApiPublicStationConfigRoute: ApiPublicStationConfigRoute,
  ApiPublicCronSyncWorkerRoute: ApiPublicCronSyncWorkerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
